# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

obj/lib-common/FLOAT.o: obj/lib-common lib-common/FLOAT.c
	gcc -m32 -fno-builtin -I$(LIB_COMMON_DIR)/include -c lib-common/FLOAT.c
	mv FLOAT.o obj/lib-common/
obj/lib-common:
	mkdir -p obj/lib-common

